name = "uno-game-server-YOURNAME" # Ganti dengan nama unik untuk Worker Anda, contoh: "uno-game-server-budi"
main = "index.js" # Ini akan menunjuk ke index.js yang ada di folder server/
compatibility_date = "2024-05-29" # Pastikan tanggal ini sama atau lebih baru dari tanggal saat ini
workers_dev = true # Opsional: Izinkan akses melalui subdomain workers.dev Anda

# Untuk pengembangan lokal, Anda mungkin ingin mengaktifkan live-reload atau mode dev
# [dev]
# ip = "0.0.0.0"
# port = 8787
# local_protocol = "http"
